name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.ps1'
    - '**.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.ps1'
    - '**.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301        
    - name: Build
      run: dotnet build
