name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: LS1
      run: ls
    - name: LS2
      run: ls /
    - name: Restore dependencies
      run: dotnet restore RabbitMQ.DependencyInjection/RabbitMQ.DependencyInjection.csproj
    - name: Build
      run: dotnet build --no-restore RabbitMQ.DependencyInjection/RabbitMQ.DependencyInjection.csproj
